#!/bin/bash

# 申请证书、检查证书
check_certificate() {
  # 申请证书
  /bin/sh /opt/ssl

  # 检查证书是否被 Let's Encrypt 成功签发
  if ls /.lego/certificates | grep "${SSL_DOMAIN}"; then
      if [ -e /.lego/certificates/"${SSL_DOMAIN}".crt ] && [ -e /.lego/certificates/"${SSL_DOMAIN}".key ]; then
          pretty_echo OK '证书签发成功!'
          # 删除原证书
          rm -rf /opt/fullchain.pem /opt/privkey.key
          # 将证书复制到特定目录
          cp /.lego/certificates/"${SSL_DOMAIN}".crt /opt/fullchain.pem
          cp /.lego/certificates/"${SSL_DOMAIN}".key /opt/privkey.key
          # 软连接证书到 nginx 配置目录
          mkdir -p /etc/nginx/conf.d/cert/
          ln -s /opt/fullchain.pem /etc/nginx/conf.d/cert/fullchain.pem
          ln -s /opt/privkey.key /etc/nginx/conf.d/cert/privkey.key

          # 判断nginx是否正在运行，如果正在运行重启 nginx
          if pgrep nginx >/dev/null; then
              pretty_echo WR "Nginx服务重载中..."
              nginx -s reload
              pretty_echo OK "Nginx服务重载成功!"
          fi
      else
          pretty_echo ER "证书签发失败!"
          exit 1
      fi
  else
      pretty_echo ER "证书签发失败!"
      exit 1
  fi
}

if [ "${SSL_ENABLE}" = "true" ]; then
  # 检查 /opt/ssl 文件是否存在
  if [ -e /opt/ssl ]; then

      # 检查证书和私钥文件是否存在
      if [ -e /opt/fullchain.pem ] && [ -e /opt/privkey.key ]; then
          # 获取当前日期和时间
          current_date=$(date +%s)
          # 提取证书的到期日期，并将其转换为 Unix 时间戳
          expiry_date=$(openssl x509 -enddate -noout -in /opt/fullchain.pem | cut -d= -f2 | awk '{sub(/ GMT/, ""); print}' | xargs -I {} date -d "{}" +%s)
          # 计算证书到期的天数
          days_until_expiry=$(( (expiry_date - current_date) / 86400 ))
          pretty_echo OK "证书剩余天数: $days_until_expiry 天。"

          # 判断证书是否在 30 天内到期
          if [ $days_until_expiry -le 30 ]; then
              pretty_echo WR "证书将在30天内到期，开始证书续订..."
              check_certificate
          else
              pretty_echo IN "证书仍然有效，无需续订。"
              # 判断nginx证书是否正确配置
              if [ ! -e /etc/nginx/conf.d/cert/fullchain.pem ] || [ ! -e /etc/nginx/conf.d/cert/privkey.key ]; then
                  # 软连接证书到 nginx 配置目录
                  mkdir -p /etc/nginx/conf.d/cert/
                  ln -s /opt/fullchain.pem /etc/nginx/conf.d/cert/fullchain.pem
                  ln -s /opt/privkey.key /etc/nginx/conf.d/cert/privkey.key
              fi
          fi
      else
          pretty_echo IN "开始申请域名证书..."
          check_certificate
      fi
  else
      pretty_echo ER "SSL证书申请脚本不存在，退出程序。"
      exit 1
  fi
else
    pretty_echo IN "内置SSL已被禁用，跳过证书检查！"

fi

