#!/bin/bash
######################
# 服务器配置，需要修改！ #
######################
SERVER=emby
SERVER_HOST=http://127.0.0.1:8096
EMBY_API_KEY=1xxxxxxxxxxxxxxxxxxxxxxxxxxxxd # 针对emby的设置， 使用plex时请注释或删除该行
EMBY_PUBLIC_ADDR=https://emby.yourdomain.com # 针对emby的设置， 使用plex时请注释或删除该行
MOUNT_PATH=/mnt # 多余路径，如/mnt/115/xxx.mkv转换到https://alist.xxx.com/d/115/xxx.mkv时，（忽略url中的前缀https://alist.xxx.com/d）相对于alist路径树的多余路径为/mnt


#####################
# alist配置，需要修改！#
#####################
ALIST_ADDR=http://127.0.0.1:5244
ALIST_TOKEN=wsdfsaafsxxxxx
ALIST_SIGNENABLE=false # alist 是否启用了 sign
ALIST_PUBLIC_ADDR=https://alist.yourdomain.com # alist 公网地址


####################################
# Emby相关配置，使用emby时才可能需要修改 #
####################################
# 图片缓存策略,包括主页、详情页、图片库的原图,路由器 nginx 请手动调小 conf 中 proxy_cache_path 的 max_size
# 0: 不同尺寸设备共用一份缓存,先访问先缓存,空间占用最小但存在小屏先缓存大屏看的图片模糊问题
# 1: 不同尺寸设备分开缓存,空间占用适中,命中率低下,但契合 emby 的图片缩放处理
# 2: 不同尺寸设备共用一份缓存,空间占用最大,移除 emby 的缩放参数,直接原图高清显示
EMBY_IMAGE_CACHE_POLICY=0 # only for emby，使用plex时请注释或删除该行


########################
# 高级配置，一般不需要修改 #
########################
# 路由规则：哪些需要302，哪些需要由本地服务器代理
# 详细说明请参考 https://github.com/chen3861229/embyExternalUrl/blob/d09f622604ac80c0b08e7102399df5d5164d6c5f/plex2Alist/nginx/conf.d/config/constant-pro.js#L22
# 如需下面的配置生效，请仅移除行首的"//"
RouteRule=$(cat <<-END
  // ["proxy", "filePath", 0, "/xxx/cd2/复杂路径/xxx1" ], // 复杂的资源命名会导nginx致劫持失败，原因：cd2中获取的路径和alist路径存在差异。不建议劫持。
END
)
# 路径映射：容器再进行路径替换时，会先将多余路径前缀MOUNT_PATH移除掉，然后根据MediaPathMapping里的规则处理。
# 详细说明请参考 https://github.com/chen3861229/embyExternalUrl/blob/d09f622604ac80c0b08e7102399df5d5164d6c5f/plex2Alist/nginx/conf.d/config/constant-pro.js#L60
# 如需下面的配置生效，请仅移除行首的"//"
MediaPathMapping=$(cat <<-END
  // [0, 3, "/Alist", ""], //去除路径中的/Alist，包含本地路径、strm文件中的路径……
  // [0, 1, "/mnt", ""], //仅处理strm文件内部为/开头的路径，将路径中的/mnt移除掉。
END
)

########################
# 基础固定配置，一般不修改 #
########################
REPO_URL=https://github.com/chen3861229/embyExternalUrl
SSL_ENABLE=false
AUTO_UPDATE=false
SOURCE_COMMIT_ID=480cfdb