name: MediaLinker Builder
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  Docker-build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: ZMediaLinker
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKERHUB_USERNAME/zmedialinker:latest -t $DOCKERHUB_USERNAME/zmedialinker:$(cat config/envs |grep SOURCE_COMMIT_ID |awk -F '=' '{print $2}') -f Dockerfile . --push